echo ""
echo ""
echo "[VIP BYPASS SPJK S10 CLOSED]"
echo "Sorry Close lebih awal,Salah sendiri di sebarin"
echo ""
echo "Jika masih ingin mengunakan BYPAS SPJK"
echo "Silahkan Perpanjang langanan VIP SPJK"
echo "hubungi telegram @admsprojecthack"
echo "WA 085859575742"
echo ""
echo "VIP SEASON 11 READY"
